[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm --workspace @gold/api run start"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
